"""empty message

Revision ID: 23f3869c2b17
Revises: 3dcfa5de37b4
Create Date: 2021-01-19 16:49:17.657825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f3869c2b17'
down_revision = '3dcfa5de37b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LENGUAJES_PROYECTOS', sa.Column('C_PROYECTO_ID', sa.Integer(), nullable=False))
    op.drop_constraint('LENGUAJES_PROYECTOS_C_TP_PROYECTO_ID_fkey', 'LENGUAJES_PROYECTOS', type_='foreignkey')
    op.create_foreign_key(None, 'LENGUAJES_PROYECTOS', 'PROYECTOS', ['C_PROYECTO_ID'], ['C_PROYECTO_ID'])
    op.drop_column('LENGUAJES_PROYECTOS', 'C_TP_PROYECTO_ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LENGUAJES_PROYECTOS', sa.Column('C_TP_PROYECTO_ID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'LENGUAJES_PROYECTOS', type_='foreignkey')
    op.create_foreign_key('LENGUAJES_PROYECTOS_C_TP_PROYECTO_ID_fkey', 'LENGUAJES_PROYECTOS', 'TIPO_PROYECTO', ['C_TP_PROYECTO_ID'], ['C_TP_PROYECTO_ID'])
    op.drop_column('LENGUAJES_PROYECTOS', 'C_PROYECTO_ID')
    # ### end Alembic commands ###
