"""Initial version

Revision ID: 3c4b11aea3cc
Revises: 
Create Date: 2021-01-23 12:10:31.190928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4b11aea3cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LENGUAJE_PROGRAMACION',
    sa.Column('C_LENGUAJE_ID', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('C_LENGUAJE_ID')
    )
    op.create_table('TIPO_PROYECTO',
    sa.Column('C_TP_PROYECTO_ID', sa.Integer(), nullable=False),
    sa.Column('D_DESCRIPCION', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('C_TP_PROYECTO_ID')
    )
    op.create_table('blog_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('PROYECTOS',
    sa.Column('C_PROYECTO_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('D_PROYECTO', sa.String(length=256), nullable=False),
    sa.Column('D_DESCRIPCION', sa.String(length=256), nullable=True),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('F_CREACION', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tipo'], ['TIPO_PROYECTO.C_TP_PROYECTO_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('C_PROYECTO_ID')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('title_slug', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_slug')
    )
    op.create_table('LENGUAJES_PROYECTOS',
    sa.Column('C_PROYECTO_ID', sa.Integer(), nullable=False),
    sa.Column('C_LENGUAJE_ID', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['C_LENGUAJE_ID'], ['LENGUAJE_PROGRAMACION.C_LENGUAJE_ID'], ),
    sa.ForeignKeyConstraint(['C_PROYECTO_ID'], ['PROYECTOS.C_PROYECTO_ID'], ),
    sa.PrimaryKeyConstraint('C_PROYECTO_ID', 'C_LENGUAJE_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LENGUAJES_PROYECTOS')
    op.drop_table('post')
    op.drop_table('PROYECTOS')
    op.drop_table('blog_user')
    op.drop_table('TIPO_PROYECTO')
    op.drop_table('LENGUAJE_PROGRAMACION')
    # ### end Alembic commands ###
