"""empty message

Revision ID: 3dcfa5de37b4
Revises: 48edd128408b
Create Date: 2021-01-19 16:37:57.125441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcfa5de37b4'
down_revision = '48edd128408b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LENGUAJE_PROGRAMACION',
    sa.Column('C_LENGUAJE_ID', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('C_LENGUAJE_ID')
    )
    op.create_table('TIPO_PROYECTO',
    sa.Column('C_TP_PROYECTO_ID', sa.Integer(), nullable=False),
    sa.Column('D_DESCRIPCION', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('C_TP_PROYECTO_ID')
    )
    op.create_table('LENGUAJES_PROYECTOS',
    sa.Column('C_TP_PROYECTO_ID', sa.Integer(), nullable=True),
    sa.Column('C_LENGUAJE_ID', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['C_LENGUAJE_ID'], ['LENGUAJE_PROGRAMACION.C_LENGUAJE_ID'], ),
    sa.ForeignKeyConstraint(['C_TP_PROYECTO_ID'], ['TIPO_PROYECTO.C_TP_PROYECTO_ID'], )
    )
    op.add_column('PROYECTOS', sa.Column('F_CREACION', sa.DateTime(), nullable=False))
    op.add_column('PROYECTOS', sa.Column('tipo', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'PROYECTOS', 'TIPO_PROYECTO', ['tipo'], ['C_TP_PROYECTO_ID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PROYECTOS', type_='foreignkey')
    op.drop_column('PROYECTOS', 'tipo')
    op.drop_column('PROYECTOS', 'F_CREACION')
    op.drop_table('LENGUAJES_PROYECTOS')
    op.drop_table('TIPO_PROYECTO')
    op.drop_table('LENGUAJE_PROGRAMACION')
    # ### end Alembic commands ###
