"""empty message

Revision ID: 48edd128408b
Revises: 33fa1803cbb3
Create Date: 2021-01-19 09:27:38.242715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48edd128408b'
down_revision = '33fa1803cbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PROYECTOS',
    sa.Column('C_PROYECTO_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('D_PROYECTO', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('C_PROYECTO_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PROYECTOS')
    # ### end Alembic commands ###
